# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'networkcreate_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_networkcreateDialogBase(object):
    def setupUi(self, networkcreateDialogBase):
        networkcreateDialogBase.setObjectName("networkcreateDialogBase")
        networkcreateDialogBase.resize(400, 330)
        self.label = QtWidgets.QLabel(networkcreateDialogBase)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 21))
        self.label.setObjectName("label")
        self.mMapLayerComboBox = QgsMapLayerComboBox(networkcreateDialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(20, 40, 361, 27))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.mMapLayerComboBox_2 = QgsMapLayerComboBox(networkcreateDialogBase)
        self.mMapLayerComboBox_2.setGeometry(QtCore.QRect(20, 80, 361, 27))
        self.mMapLayerComboBox_2.setObjectName("mMapLayerComboBox_2")
        self.mMapLayerComboBox_3 = QgsMapLayerComboBox(networkcreateDialogBase)
        self.mMapLayerComboBox_3.setGeometry(QtCore.QRect(20, 120, 361, 27))
        self.mMapLayerComboBox_3.setObjectName("mMapLayerComboBox_3")
        self.Buildingconnection = QtWidgets.QLabel(networkcreateDialogBase)
        self.Buildingconnection.setGeometry(QtCore.QRect(20, 210, 131, 21))
        self.Buildingconnection.setObjectName("Buildingconnection")
        self.createConnectionButton = QtWidgets.QPushButton(networkcreateDialogBase)
        self.createConnectionButton.setGeometry(QtCore.QRect(20, 240, 161, 23))
        self.createConnectionButton.setObjectName("createConnectionButton")
        self.crt = QtWidgets.QPushButton(networkcreateDialogBase)
        self.crt.setGeometry(QtCore.QRect(220, 240, 161, 23))
        self.crt.setObjectName("crt")
        self.label_2 = QtWidgets.QLabel(networkcreateDialogBase)
        self.label_2.setGeometry(QtCore.QRect(220, 210, 151, 16))
        self.label_2.setObjectName("label_2")
        self.roadsLayer = QtWidgets.QComboBox(networkcreateDialogBase)
        self.roadsLayer.setGeometry(QtCore.QRect(20, 180, 161, 22))
        self.roadsLayer.setObjectName("roadsLayer")
        self.buildingsLayer = QtWidgets.QComboBox(networkcreateDialogBase)
        self.buildingsLayer.setGeometry(QtCore.QRect(220, 180, 161, 22))
        self.buildingsLayer.setObjectName("buildingsLayer")
        self.Selectr = QtWidgets.QLabel(networkcreateDialogBase)
        self.Selectr.setGeometry(QtCore.QRect(20, 160, 151, 16))
        self.Selectr.setObjectName("Selectr")
        self.label_4 = QtWidgets.QLabel(networkcreateDialogBase)
        self.label_4.setGeometry(QtCore.QRect(220, 160, 161, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(networkcreateDialogBase)
        QtCore.QMetaObject.connectSlotsByName(networkcreateDialogBase)

    def retranslateUi(self, networkcreateDialogBase):
        _translate = QtCore.QCoreApplication.translate
        networkcreateDialogBase.setWindowTitle(_translate("networkcreateDialogBase", "Network_creator"))
        self.label.setText(_translate("networkcreateDialogBase", "Select layer:"))
        self.Buildingconnection.setText(_translate("networkcreateDialogBase", "Building connection:"))
        self.createConnectionButton.setText(_translate("networkcreateDialogBase", "Run"))
        self.crt.setText(_translate("networkcreateDialogBase", "Create"))
        self.label_2.setText(_translate("networkcreateDialogBase", "Create network:"))
        self.Selectr.setText(_translate("networkcreateDialogBase", "Select road layer:"))
        self.label_4.setText(_translate("networkcreateDialogBase", "Select buldings layer:"))
from qgsmaplayercombobox import QgsMapLayerComboBox
